package com.unbosque.fifasketch.modelo;
// Generated 30/04/2018 03:49:09 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CopasMundo generated by hbm2java
 */
public class CopasMundo implements java.io.Serializable {

	private Integer idCopasMundo;
	private Pais pais;
	private Date ano;
	private Set participacioneses = new HashSet(0);

	public CopasMundo() {
	}

	public CopasMundo(Pais pais, Date ano) {
		this.pais = pais;
		this.ano = ano;
	}

	public CopasMundo(Pais pais, Date ano, Set participacioneses) {
		this.pais = pais;
		this.ano = ano;
		this.participacioneses = participacioneses;
	}

	public Integer getIdCopasMundo() {
		return this.idCopasMundo;
	}

	public void setIdCopasMundo(Integer idCopasMundo) {
		this.idCopasMundo = idCopasMundo;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Date getAno() {
		return this.ano;
	}

	public void setAno(Date ano) {
		this.ano = ano;
	}

	public Set getParticipacioneses() {
		return this.participacioneses;
	}

	public void setParticipacioneses(Set participacioneses) {
		this.participacioneses = participacioneses;
	}

}
