package com.unbosque.fifasketch.modelo;
// Generated 1/05/2018 02:13:37 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * FaseTorneo generated by hbm2java
 */
public class FaseTorneo implements java.io.Serializable {

	private Integer idFaseTorneo;
	private String fase;
	private Set partidos = new HashSet(0);

	public FaseTorneo() {
	}

	public FaseTorneo(String fase, Set partidos) {
		this.fase = fase;
		this.partidos = partidos;
	}

	public Integer getIdFaseTorneo() {
		return this.idFaseTorneo;
	}

	public void setIdFaseTorneo(Integer idFaseTorneo) {
		this.idFaseTorneo = idFaseTorneo;
	}

	public String getFase() {
		return this.fase;
	}

	public void setFase(String fase) {
		this.fase = fase;
	}

	public Set getPartidos() {
		return this.partidos;
	}

	public void setPartidos(Set partidos) {
		this.partidos = partidos;
	}

}
