package com.unbosque.fifasketch.modelo;
// Generated 30/04/2018 03:49:09 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

	private int idGrupo;
	private String grupo;
	private Set equipos = new HashSet(0);

	public Grupo() {
	}

	public Grupo(int idGrupo, String grupo) {
		this.idGrupo = idGrupo;
		this.grupo = grupo;
	}

	public Grupo(int idGrupo, String grupo, Set equipos) {
		this.idGrupo = idGrupo;
		this.grupo = grupo;
		this.equipos = equipos;
	}

	public int getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(int idGrupo) {
		this.idGrupo = idGrupo;
	}

	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

}
