package com.unbosque.fifasketch.modelo;
// Generated 1/05/2018 02:13:37 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPais;
	private String nombrePais;
	private Set equipos = new HashSet(0);

	public Pais() {
	}

	public Pais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public Pais(String nombrePais, Set equipos) {
		this.nombrePais = nombrePais;
		this.equipos = equipos;
	}

	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	public String getNombrePais() {
		return this.nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

}
