package com.unbosque.fifasketch.modelo;
// Generated 30/04/2018 03:49:09 PM by Hibernate Tools 5.1.7.Final

/**
 * Participaciones generated by hbm2java
 */
public class Participaciones implements java.io.Serializable {

	private ParticipacionesId id;
	private CopasMundo copasMundo;
	private Equipo equipo;

	public Participaciones() {
	}

	public Participaciones(ParticipacionesId id) {
		this.id = id;
	}

	public Participaciones(ParticipacionesId id, CopasMundo copasMundo, Equipo equipo) {
		this.id = id;
		this.copasMundo = copasMundo;
		this.equipo = equipo;
	}

	public ParticipacionesId getId() {
		return this.id;
	}

	public void setId(ParticipacionesId id) {
		this.id = id;
	}

	public CopasMundo getCopasMundo() {
		return this.copasMundo;
	}

	public void setCopasMundo(CopasMundo copasMundo) {
		this.copasMundo = copasMundo;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

}
