package com.unbosque.fifasketch.modelo;
// Generated 30/04/2018 03:49:09 PM by Hibernate Tools 5.1.7.Final

/**
 * ParticipacionesId generated by hbm2java
 */
public class ParticipacionesId implements java.io.Serializable {

	private Integer idCopasMundo;
	private Integer idEquipo;

	public ParticipacionesId() {
	}

	public ParticipacionesId(Integer idCopasMundo, Integer idEquipo) {
		this.idCopasMundo = idCopasMundo;
		this.idEquipo = idEquipo;
	}

	public Integer getIdCopasMundo() {
		return this.idCopasMundo;
	}

	public void setIdCopasMundo(Integer idCopasMundo) {
		this.idCopasMundo = idCopasMundo;
	}

	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParticipacionesId))
			return false;
		ParticipacionesId castOther = (ParticipacionesId) other;

		return ((this.getIdCopasMundo() == castOther.getIdCopasMundo()) || (this.getIdCopasMundo() != null
				&& castOther.getIdCopasMundo() != null && this.getIdCopasMundo().equals(castOther.getIdCopasMundo())))
				&& ((this.getIdEquipo() == castOther.getIdEquipo()) || (this.getIdEquipo() != null
						&& castOther.getIdEquipo() != null && this.getIdEquipo().equals(castOther.getIdEquipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCopasMundo() == null ? 0 : this.getIdCopasMundo().hashCode());
		result = 37 * result + (getIdEquipo() == null ? 0 : this.getIdEquipo().hashCode());
		return result;
	}

}
