package com.unbosque.fifasketch.modelo;
// Generated 1/05/2018 02:13:37 PM by Hibernate Tools 5.1.7.Final

/**
 * ParticipacionesId generated by hbm2java
 */
public class ParticipacionesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCopasMundo;
	private Integer idEquipo;
	private Byte participo;

	public ParticipacionesId() {
	}

	public ParticipacionesId(Integer idCopasMundo, Integer idEquipo, Byte participo) {
		this.idCopasMundo = idCopasMundo;
		this.idEquipo = idEquipo;
		this.participo = participo;
	}

	public Integer getIdCopasMundo() {
		return this.idCopasMundo;
	}

	public void setIdCopasMundo(Integer idCopasMundo) {
		this.idCopasMundo = idCopasMundo;
	}

	public Integer getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(Integer idEquipo) {
		this.idEquipo = idEquipo;
	}

	public Byte getParticipo() {
		return this.participo;
	}

	public void setParticipo(Byte participo) {
		this.participo = participo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParticipacionesId))
			return false;
		ParticipacionesId castOther = (ParticipacionesId) other;

		return ((this.getIdCopasMundo() == castOther.getIdCopasMundo()) || (this.getIdCopasMundo() != null
				&& castOther.getIdCopasMundo() != null && this.getIdCopasMundo().equals(castOther.getIdCopasMundo())))
				&& ((this.getIdEquipo() == castOther.getIdEquipo()) || (this.getIdEquipo() != null
						&& castOther.getIdEquipo() != null && this.getIdEquipo().equals(castOther.getIdEquipo())))
				&& ((this.getParticipo() == castOther.getParticipo()) || (this.getParticipo() != null
						&& castOther.getParticipo() != null && this.getParticipo().equals(castOther.getParticipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCopasMundo() == null ? 0 : this.getIdCopasMundo().hashCode());
		result = 37 * result + (getIdEquipo() == null ? 0 : this.getIdEquipo().hashCode());
		result = 37 * result + (getParticipo() == null ? 0 : this.getParticipo().hashCode());
		return result;
	}

}
