package com.unbosque.fifasketch.modelo;
// Generated 30/04/2018 03:49:09 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tecnico generated by hbm2java
 */
public class Tecnico implements java.io.Serializable {

	private Integer idTecnico;
	private String nombre;
	private String apellido;
	private Date fechaNacimiento;
	private int idEquipo;
	private Set equipos = new HashSet(0);

	public Tecnico() {
	}

	public Tecnico(String nombre, String apellido, int idEquipo) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.idEquipo = idEquipo;
	}

	public Tecnico(String nombre, String apellido, Date fechaNacimiento, int idEquipo, Set equipos) {
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaNacimiento = fechaNacimiento;
		this.idEquipo = idEquipo;
		this.equipos = equipos;
	}

	public Integer getIdTecnico() {
		return this.idTecnico;
	}

	public void setIdTecnico(Integer idTecnico) {
		this.idTecnico = idTecnico;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public int getIdEquipo() {
		return this.idEquipo;
	}

	public void setIdEquipo(int idEquipo) {
		this.idEquipo = idEquipo;
	}

	public Set getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set equipos) {
		this.equipos = equipos;
	}

}
